// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKFh7cK9sCeil9772qC4vbxhQSX9gLhbw',
    appId: '1:655634459041:web:8d95d1d3b3d129189903e0',
    messagingSenderId: '655634459041',
    projectId: 'lab4-1db07',
    authDomain: 'lab4-1db07.firebaseapp.com',
    storageBucket: 'lab4-1db07.firebasestorage.app',
    measurementId: 'G-LSCGFYVNSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq5ev10NbgAXPIoFDZUwC41wFvO6oYu2c',
    appId: '1:655634459041:android:fe34f824c98516359903e0',
    messagingSenderId: '655634459041',
    projectId: 'lab4-1db07',
    storageBucket: 'lab4-1db07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa7m_1MsBuGbmVE5gjslUxgkiSHZJwRdg',
    appId: '1:655634459041:ios:c32c5832469e9c3b9903e0',
    messagingSenderId: '655634459041',
    projectId: 'lab4-1db07',
    storageBucket: 'lab4-1db07.firebasestorage.app',
    iosBundleId: 'com.example.ngongocduy7884',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa7m_1MsBuGbmVE5gjslUxgkiSHZJwRdg',
    appId: '1:655634459041:ios:c32c5832469e9c3b9903e0',
    messagingSenderId: '655634459041',
    projectId: 'lab4-1db07',
    storageBucket: 'lab4-1db07.firebasestorage.app',
    iosBundleId: 'com.example.ngongocduy7884',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKFh7cK9sCeil9772qC4vbxhQSX9gLhbw',
    appId: '1:655634459041:web:655a002306fd16c19903e0',
    messagingSenderId: '655634459041',
    projectId: 'lab4-1db07',
    authDomain: 'lab4-1db07.firebaseapp.com',
    storageBucket: 'lab4-1db07.firebasestorage.app',
    measurementId: 'G-RMX20RRKPD',
  );
}
